#!/bin/bash
# https://www.digitalocean.com/community/tutorials/how-to-write-unit-tests-in-go-using-go-test-and-the-testing-package
go test -v -cpu=2 -bench=./... ./tests/...
go test -v -coverprofile=c.out -coverpkg ./... ./tests/...
go tool cover -html=c.out -o coverage.html